const fs = require('fs').promises
const db = require('./db.js')
const bot = require('mwbot')
const atl = require('atlas-parser')
const jimp = require('jimp')
const cliProgress = require('cli-progress')
const { apiUrl, apiLimit, concurrency } = require('./mwconfig.json')
const { item, license } = require('./wiki.js')
const { str, stagger, mwContinuedRequest } = require('./util.js')
const toString = (o) => o.toString()

const client = new bot({
  verbose: false,
  silent: true,
  concurrency
})

const DRY = process.env.DRY === '1'
const OW = process.env.OW === '1'
const OWI = process.env.OWI === '1'
const DMP = process.env.DMP === '1'

const prog = new cliProgress.SingleBar(
  {
    format: '{bar} | {percentage}% | ETA: {eta}s | {value}/{total} | {name}'
  },
  cliProgress.Presets.shades_classic
)
prog.increment = prog.increment.bind(prog)
prog.stop = prog.stop.bind(prog)

Promise.all([
  fs
    .readFile('./credentials.secret')
    .then(toString)
    .then((str) => str.split('\n')),
  fs.readFile('./lib/nv/gamedata.json').then(toString).then(JSON.parse),
  fs.readFile('./lib/nv/UI.atlas').then(str).then(atl.parse),
  jimp.read('./lib/nv/UI.png')
]).then(async ([[username, password], data, ui, UI]) => {
  const $db = db(data)
  const eq = await $db.equipment()

  if (DMP) {
    console.log(eq.map(item).join('\n\n'))
    return
  }

  const { csrftoken: token } = await client.loginGetEditToken({
    apiUrl,
    username,
    password
  })

  // --- Images --- //

  const exImgs = await mwContinuedRequest(client, {
    action: 'query',
    list: 'allimages',
    ailimit: 500,
    token
  }).then((imgs) => {
    return imgs.map((i) => i.name.toLowerCase().replace('_', '/').slice(0, -4))
  })
  const imgs = Object.entries(ui['UI.png'].frames).filter(
    ([k]) => k.includes('icons') && (OWI || !exImgs.includes(k))
  )

  console.log('\nUploading images:\n')
  prog.start(imgs.length, 0, { name: '' })

  const timeStep = Math.ceil(apiLimit.period / apiLimit.count)
  await stagger(imgs, timeStep, async ([k, [v]], i) => {
    const fname = k.replace('/', '_') + '.png'
    prog.update(i + 1, { name: fname })

    const fPath = `./dist/${fname}`
    await UI.clone()
      .crop(...v.xy, ...v.size)
      .writeAsync(fPath)

    if (DRY) return

    return client
      .upload(fname, `./dist/${fname}`, 'Uploaded by nvwikibot', {
        text: license('Casey Clyde'),
        ignorewarnings: OWI
      })
      .catch(console.error)
  }).finally(prog.stop)

  // --- Items --- //

  const exItems = await mwContinuedRequest(client, {
    action: 'query',
    list: 'allpages',
    aplimit: 500,
    token
  }).then((pages) => pages.map((i) => i.title))
  const items = eq.filter((i) => OW || !exItems.includes(i.name))

  console.log('\nUpdating items:\n')
  prog.start(items.length, 0, { name: '' })

  stagger(items, timeStep, (itm, i) => {
    prog.update(i + 1, { name: itm.name })
    const content = item(itm)

    if (DMP) console.log(content)
    if (DRY) return

    return client
      .edit(itm.name, content, 'Generated by nvwikibot', { token })
      .catch(console.error)
  }).finally(prog.stop)
})
